FROM nginx

COPY default.conf /etc/nginx/config.d/default.conf
COPY default.conf /etc/nginx/conf.d/default.conf

COPY ./dist-testing /usr/share/nginx/html

RUN  ["rm", "-rf", "/etc/localtime"]

RUN  ["ln", "-s", "/usr/share/zoneinfo/Asia/Ho_Chi_Minh", "/etc/localtime"]